services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_CONTAINER_PORT}"
    environment:
      - API_BASE_URL=${VITE_API_BASE_URL}
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env

volumes:
  rivy_data: